export const formFields = [
  { name: "fullName", label: "Full Name", type: "text", required: true, minLength: 3 },
  { name: "email", label: "Email", type: "email", required: true, pattern: /^\S+@\S+\.\S+$/ },
  { name: "age", label: "Age", type: "number", required: true, min: 18, max: 99 },
  { name: "phone", label: "Phone", type: "tel", required: true, pattern: /^[0-9]{10}$/ },
  { name: "address", label: "Address", type: "text", required: true, minLength: 10 },
  { name: "city", label: "City", type: "text", required: true },
  { name: "country", label: "Country", type: "text", required: true },
  { name: "zipCode", label: "Zip Code", type: "text", required: true, pattern: /^[0-9]{5}$/ },
  { name: "username", label: "Username", type: "text", required: true, minLength: 5 },
  { name: "password", label: "Password", type: "password", required: true, minLength: 8 },
  { name: "confirmPassword", label: "Confirm Password", type: "password", required: true },
  { name: "gender", label: "Gender", type: "text", required: true },
  { name: "birthDate", label: "Birth Date", type: "date", required: true },
  { name: "occupation", label: "Occupation", type: "text" },
  { name: "company", label: "Company", type: "text" },
  { name: "website", label: "Website", type: "url" },
  { name: "bio", label: "Short Bio", type: "text", minLength: 20 },
  { name: "skills", label: "Skills", type: "text" },
  { name: "linkedin", label: "LinkedIn", type: "url" },
  { name: "github", label: "GitHub", type: "url" },
];
